# Generated by Django 3.2.4 on 2021-06-28 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('instagram', models.CharField(blank=True, max_length=40)),
                ('snapchat', models.CharField(blank=True, max_length=40)),
                ('twitter', models.CharField(blank=True, max_length=40)),
                ('reddit', models.CharField(blank=True, max_length=40)),
                ('facebook', models.CharField(blank=True, max_length=40)),
                ('phone_num', models.CharField(blank=True, max_length=40)),
                ('linkedin', models.CharField(blank=True, max_length=40)),
                ('youtube', models.CharField(blank=True, max_length=40)),
                ('clubhouse', models.CharField(blank=True, max_length=40)),
                ('gmail', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
