# Generated by Django 3.2.4 on 2021-06-29 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialsharingapp', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
