# Generated by Django 3.2.4 on 2021-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsharingapp', '0003_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='image.jpg', upload_to='photo'),
        ),
    ]
