# Generated by Django 3.2.4 on 2021-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsharingapp', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photo/image.jpg', upload_to='photo'),
        ),
    ]
